"""Add password reset fields to user

Revision ID: 0ba9ef8aa21c
Revises: c3d4e5f6a7b8
Create Date: 2026-05-03 14:40:24.184460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ba9ef8aa21c'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # FIX: Added proper constraint name 'uq_password_reset_token' for password reset functionality
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token_expiry', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_password_reset_token', ['password_reset_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_password_reset_token', type_='unique')
        batch_op.drop_column('password_reset_token_expiry')
        batch_op.drop_column('password_reset_token')

    # ### end Alembic commands ###
