"""add preferMetric to user

Revision ID: 203807ef88c1
Revises: 8ce0ee69a285
Create Date: 2026-04-27 15:23:23.381267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203807ef88c1'
down_revision = '8ce0ee69a285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferMetric', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferMetric')

    # ### end Alembic commands ###
