"""add disableNotifications to user

Revision ID: 63072babfd6e
Revises: 203807ef88c1
Create Date: 2026-04-27 15:29:50.940689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63072babfd6e'
down_revision = '203807ef88c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disableNotifications', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('disableNotifications')

    # ### end Alembic commands ###
