"""add image to recipe and avatar to user

Revision ID: 8ce0ee69a285
Revises: f1a13656e60d
Create Date: 2026-04-27 14:40:47.710166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce0ee69a285'
down_revision = 'f1a13656e60d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
