"""add groups feature

Revision ID: f1a13656e60d
Revises: 
Create Date: 2026-04-18 09:16:44.903123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a13656e60d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leaderID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['leaderID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('dateJoined', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['groupID'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupID', sa.Integer(), nullable=False),
    sa.Column('senderID', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('dateSent', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['groupID'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['senderID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupID', sa.Integer(), nullable=False),
    sa.Column('recipeID', sa.Integer(), nullable=False),
    sa.Column('sharedByID', sa.Integer(), nullable=False),
    sa.Column('dateSaved', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['groupID'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['recipeID'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['sharedByID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_recipes')
    op.drop_table('group_messages')
    op.drop_table('group_members')
    op.drop_table('groups')
    # ### end Alembic commands ###
